name: Continuous Delivery
on:
  push:
    branches:
      - main

jobs:
  devliver:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Simulando Continuous Delivery
        uses: actions/upload-artifact@v4
        with:
          name: projetozipado
          path: |
            **.py
            README.md

  deploy:
    needs: devliver
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: projetozipado
      - name: Display structure of downloaded files
        run: ls -R